// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library.proto

package com.szymon_kaluza.protobuf.proto.model;

public interface AuthorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Author)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string surname = 2;</code>
   * @return Whether the surname field is set.
   */
  boolean hasSurname();
  /**
   * <code>optional string surname = 2;</code>
   * @return The surname.
   */
  java.lang.String getSurname();
  /**
   * <code>optional string surname = 2;</code>
   * @return The bytes for surname.
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>optional string nationality = 3;</code>
   * @return Whether the nationality field is set.
   */
  boolean hasNationality();
  /**
   * <code>optional string nationality = 3;</code>
   * @return The nationality.
   */
  java.lang.String getNationality();
  /**
   * <code>optional string nationality = 3;</code>
   * @return The bytes for nationality.
   */
  com.google.protobuf.ByteString
      getNationalityBytes();
}
