// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library.proto

package com.szymon_kaluza.protobuf.proto.model;

/**
 * Protobuf type {@code protobuf.Library}
 */
public final class Library extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.Library)
    LibraryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Library.newBuilder() to construct.
  private Library(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Library() {
    address_ = "";
    books_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Library();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.szymon_kaluza.protobuf.proto.model.LibraryProtos.internal_static_protobuf_Library_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.szymon_kaluza.protobuf.proto.model.LibraryProtos.internal_static_protobuf_Library_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.szymon_kaluza.protobuf.proto.model.Library.class, com.szymon_kaluza.protobuf.proto.model.Library.Builder.class);
  }

  private int bitField0_;
  public static final int ADDRESS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object address_ = "";
  /**
   * <code>optional string address = 1;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string address = 1;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>optional string address = 1;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOOKS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.szymon_kaluza.protobuf.proto.model.Book> books_;
  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.szymon_kaluza.protobuf.proto.model.Book> getBooksList() {
    return books_;
  }
  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.szymon_kaluza.protobuf.proto.model.BookOrBuilder> 
      getBooksOrBuilderList() {
    return books_;
  }
  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  @java.lang.Override
  public int getBooksCount() {
    return books_.size();
  }
  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  @java.lang.Override
  public com.szymon_kaluza.protobuf.proto.model.Book getBooks(int index) {
    return books_.get(index);
  }
  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  @java.lang.Override
  public com.szymon_kaluza.protobuf.proto.model.BookOrBuilder getBooksOrBuilder(
      int index) {
    return books_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
    }
    for (int i = 0; i < books_.size(); i++) {
      output.writeMessage(2, books_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
    }
    for (int i = 0; i < books_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, books_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.szymon_kaluza.protobuf.proto.model.Library)) {
      return super.equals(obj);
    }
    com.szymon_kaluza.protobuf.proto.model.Library other = (com.szymon_kaluza.protobuf.proto.model.Library) obj;

    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getBooksList()
        .equals(other.getBooksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (getBooksCount() > 0) {
      hash = (37 * hash) + BOOKS_FIELD_NUMBER;
      hash = (53 * hash) + getBooksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.szymon_kaluza.protobuf.proto.model.Library parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.szymon_kaluza.protobuf.proto.model.Library prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.Library}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.Library)
      com.szymon_kaluza.protobuf.proto.model.LibraryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.szymon_kaluza.protobuf.proto.model.LibraryProtos.internal_static_protobuf_Library_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.szymon_kaluza.protobuf.proto.model.LibraryProtos.internal_static_protobuf_Library_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.szymon_kaluza.protobuf.proto.model.Library.class, com.szymon_kaluza.protobuf.proto.model.Library.Builder.class);
    }

    // Construct using com.szymon_kaluza.protobuf.proto.model.Library.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      address_ = "";
      if (booksBuilder_ == null) {
        books_ = java.util.Collections.emptyList();
      } else {
        books_ = null;
        booksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.szymon_kaluza.protobuf.proto.model.LibraryProtos.internal_static_protobuf_Library_descriptor;
    }

    @java.lang.Override
    public com.szymon_kaluza.protobuf.proto.model.Library getDefaultInstanceForType() {
      return com.szymon_kaluza.protobuf.proto.model.Library.getDefaultInstance();
    }

    @java.lang.Override
    public com.szymon_kaluza.protobuf.proto.model.Library build() {
      com.szymon_kaluza.protobuf.proto.model.Library result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.szymon_kaluza.protobuf.proto.model.Library buildPartial() {
      com.szymon_kaluza.protobuf.proto.model.Library result = new com.szymon_kaluza.protobuf.proto.model.Library(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.szymon_kaluza.protobuf.proto.model.Library result) {
      if (booksBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          books_ = java.util.Collections.unmodifiableList(books_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.books_ = books_;
      } else {
        result.books_ = booksBuilder_.build();
      }
    }

    private void buildPartial0(com.szymon_kaluza.protobuf.proto.model.Library result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.address_ = address_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.szymon_kaluza.protobuf.proto.model.Library) {
        return mergeFrom((com.szymon_kaluza.protobuf.proto.model.Library)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.szymon_kaluza.protobuf.proto.model.Library other) {
      if (other == com.szymon_kaluza.protobuf.proto.model.Library.getDefaultInstance()) return this;
      if (other.hasAddress()) {
        address_ = other.address_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (booksBuilder_ == null) {
        if (!other.books_.isEmpty()) {
          if (books_.isEmpty()) {
            books_ = other.books_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBooksIsMutable();
            books_.addAll(other.books_);
          }
          onChanged();
        }
      } else {
        if (!other.books_.isEmpty()) {
          if (booksBuilder_.isEmpty()) {
            booksBuilder_.dispose();
            booksBuilder_ = null;
            books_ = other.books_;
            bitField0_ = (bitField0_ & ~0x00000002);
            booksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBooksFieldBuilder() : null;
          } else {
            booksBuilder_.addAllMessages(other.books_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              address_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.szymon_kaluza.protobuf.proto.model.Book m =
                  input.readMessage(
                      com.szymon_kaluza.protobuf.proto.model.Book.parser(),
                      extensionRegistry);
              if (booksBuilder_ == null) {
                ensureBooksIsMutable();
                books_.add(m);
              } else {
                booksBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object address_ = "";
    /**
     * <code>optional string address = 1;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string address = 1;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string address = 1;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string address = 1;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      address_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      address_ = getDefaultInstance().getAddress();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 1;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      address_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.szymon_kaluza.protobuf.proto.model.Book> books_ =
      java.util.Collections.emptyList();
    private void ensureBooksIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        books_ = new java.util.ArrayList<com.szymon_kaluza.protobuf.proto.model.Book>(books_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.szymon_kaluza.protobuf.proto.model.Book, com.szymon_kaluza.protobuf.proto.model.Book.Builder, com.szymon_kaluza.protobuf.proto.model.BookOrBuilder> booksBuilder_;

    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public java.util.List<com.szymon_kaluza.protobuf.proto.model.Book> getBooksList() {
      if (booksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(books_);
      } else {
        return booksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public int getBooksCount() {
      if (booksBuilder_ == null) {
        return books_.size();
      } else {
        return booksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public com.szymon_kaluza.protobuf.proto.model.Book getBooks(int index) {
      if (booksBuilder_ == null) {
        return books_.get(index);
      } else {
        return booksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public Builder setBooks(
        int index, com.szymon_kaluza.protobuf.proto.model.Book value) {
      if (booksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.set(index, value);
        onChanged();
      } else {
        booksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public Builder setBooks(
        int index, com.szymon_kaluza.protobuf.proto.model.Book.Builder builderForValue) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.set(index, builderForValue.build());
        onChanged();
      } else {
        booksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public Builder addBooks(com.szymon_kaluza.protobuf.proto.model.Book value) {
      if (booksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.add(value);
        onChanged();
      } else {
        booksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public Builder addBooks(
        int index, com.szymon_kaluza.protobuf.proto.model.Book value) {
      if (booksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.add(index, value);
        onChanged();
      } else {
        booksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public Builder addBooks(
        com.szymon_kaluza.protobuf.proto.model.Book.Builder builderForValue) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.add(builderForValue.build());
        onChanged();
      } else {
        booksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public Builder addBooks(
        int index, com.szymon_kaluza.protobuf.proto.model.Book.Builder builderForValue) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.add(index, builderForValue.build());
        onChanged();
      } else {
        booksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public Builder addAllBooks(
        java.lang.Iterable<? extends com.szymon_kaluza.protobuf.proto.model.Book> values) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, books_);
        onChanged();
      } else {
        booksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public Builder clearBooks() {
      if (booksBuilder_ == null) {
        books_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        booksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public Builder removeBooks(int index) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.remove(index);
        onChanged();
      } else {
        booksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public com.szymon_kaluza.protobuf.proto.model.Book.Builder getBooksBuilder(
        int index) {
      return getBooksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public com.szymon_kaluza.protobuf.proto.model.BookOrBuilder getBooksOrBuilder(
        int index) {
      if (booksBuilder_ == null) {
        return books_.get(index);  } else {
        return booksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public java.util.List<? extends com.szymon_kaluza.protobuf.proto.model.BookOrBuilder> 
         getBooksOrBuilderList() {
      if (booksBuilder_ != null) {
        return booksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(books_);
      }
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public com.szymon_kaluza.protobuf.proto.model.Book.Builder addBooksBuilder() {
      return getBooksFieldBuilder().addBuilder(
          com.szymon_kaluza.protobuf.proto.model.Book.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public com.szymon_kaluza.protobuf.proto.model.Book.Builder addBooksBuilder(
        int index) {
      return getBooksFieldBuilder().addBuilder(
          index, com.szymon_kaluza.protobuf.proto.model.Book.getDefaultInstance());
    }
    /**
     * <code>repeated .protobuf.Book books = 2;</code>
     */
    public java.util.List<com.szymon_kaluza.protobuf.proto.model.Book.Builder> 
         getBooksBuilderList() {
      return getBooksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.szymon_kaluza.protobuf.proto.model.Book, com.szymon_kaluza.protobuf.proto.model.Book.Builder, com.szymon_kaluza.protobuf.proto.model.BookOrBuilder> 
        getBooksFieldBuilder() {
      if (booksBuilder_ == null) {
        booksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.szymon_kaluza.protobuf.proto.model.Book, com.szymon_kaluza.protobuf.proto.model.Book.Builder, com.szymon_kaluza.protobuf.proto.model.BookOrBuilder>(
                books_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        books_ = null;
      }
      return booksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.Library)
  }

  // @@protoc_insertion_point(class_scope:protobuf.Library)
  private static final com.szymon_kaluza.protobuf.proto.model.Library DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.szymon_kaluza.protobuf.proto.model.Library();
  }

  public static com.szymon_kaluza.protobuf.proto.model.Library getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Library>
      PARSER = new com.google.protobuf.AbstractParser<Library>() {
    @java.lang.Override
    public Library parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Library> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Library> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.szymon_kaluza.protobuf.proto.model.Library getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

