/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.szymon_kaluza.protobuf_avro.avro.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class Author extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3700152646064468096L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Author\",\"namespace\":\"com.szymon_kaluza.protobuf_avro.avro.model\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"surname\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"nationality\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Author> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Author> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Author> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Author> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Author> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Author to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Author from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Author instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Author fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private CharSequence name;
  private CharSequence surname;
  private CharSequence nationality;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Author() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param surname The new value for surname
   * @param nationality The new value for nationality
   */
  public Author(CharSequence name, CharSequence surname, CharSequence nationality) {
    this.name = name;
    this.surname = surname;
    this.nationality = nationality;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return surname;
    case 2: return nationality;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: name = (CharSequence)value$; break;
    case 1: surname = (CharSequence)value$; break;
    case 2: nationality = (CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'surname' field.
   * @return The value of the 'surname' field.
   */
  public CharSequence getSurname() {
    return surname;
  }


  /**
   * Sets the value of the 'surname' field.
   * @param value the value to set.
   */
  public void setSurname(CharSequence value) {
    this.surname = value;
  }

  /**
   * Gets the value of the 'nationality' field.
   * @return The value of the 'nationality' field.
   */
  public CharSequence getNationality() {
    return nationality;
  }


  /**
   * Sets the value of the 'nationality' field.
   * @param value the value to set.
   */
  public void setNationality(CharSequence value) {
    this.nationality = value;
  }

  /**
   * Creates a new Author RecordBuilder.
   * @return A new Author RecordBuilder
   */
  public static com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder newBuilder() {
    return new com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder();
  }

  /**
   * Creates a new Author RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Author RecordBuilder
   */
  public static com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder newBuilder(com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder other) {
    if (other == null) {
      return new com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder();
    } else {
      return new com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder(other);
    }
  }

  /**
   * Creates a new Author RecordBuilder by copying an existing Author instance.
   * @param other The existing instance to copy.
   * @return A new Author RecordBuilder
   */
  public static com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder newBuilder(com.szymon_kaluza.protobuf_avro.avro.model.Author other) {
    if (other == null) {
      return new com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder();
    } else {
      return new com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder(other);
    }
  }

  /**
   * RecordBuilder for Author instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Author>
    implements org.apache.avro.data.RecordBuilder<Author> {

    private CharSequence name;
    private CharSequence surname;
    private CharSequence nationality;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.surname)) {
        this.surname = data().deepCopy(fields()[1].schema(), other.surname);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.nationality)) {
        this.nationality = data().deepCopy(fields()[2].schema(), other.nationality);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Author instance
     * @param other The existing instance to copy.
     */
    private Builder(com.szymon_kaluza.protobuf_avro.avro.model.Author other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.surname)) {
        this.surname = data().deepCopy(fields()[1].schema(), other.surname);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.nationality)) {
        this.nationality = data().deepCopy(fields()[2].schema(), other.nationality);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder setName(CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'surname' field.
      * @return The value.
      */
    public CharSequence getSurname() {
      return surname;
    }


    /**
      * Sets the value of the 'surname' field.
      * @param value The value of 'surname'.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder setSurname(CharSequence value) {
      validate(fields()[1], value);
      this.surname = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'surname' field has been set.
      * @return True if the 'surname' field has been set, false otherwise.
      */
    public boolean hasSurname() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'surname' field.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder clearSurname() {
      surname = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'nationality' field.
      * @return The value.
      */
    public CharSequence getNationality() {
      return nationality;
    }


    /**
      * Sets the value of the 'nationality' field.
      * @param value The value of 'nationality'.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder setNationality(CharSequence value) {
      validate(fields()[2], value);
      this.nationality = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'nationality' field has been set.
      * @return True if the 'nationality' field has been set, false otherwise.
      */
    public boolean hasNationality() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'nationality' field.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Author.Builder clearNationality() {
      nationality = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Author build() {
      try {
        Author record = new Author();
        record.name = fieldSetFlags()[0] ? this.name : (CharSequence) defaultValue(fields()[0]);
        record.surname = fieldSetFlags()[1] ? this.surname : (CharSequence) defaultValue(fields()[1]);
        record.nationality = fieldSetFlags()[2] ? this.nationality : (CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Author>
    WRITER$ = (org.apache.avro.io.DatumWriter<Author>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Author>
    READER$ = (org.apache.avro.io.DatumReader<Author>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    if (this.surname == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.surname);
    }

    if (this.nationality == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.nationality);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.surname = null;
      } else {
        this.surname = in.readString(this.surname instanceof Utf8 ? (Utf8)this.surname : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.nationality = null;
      } else {
        this.nationality = in.readString(this.nationality instanceof Utf8 ? (Utf8)this.nationality : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.surname = null;
          } else {
            this.surname = in.readString(this.surname instanceof Utf8 ? (Utf8)this.surname : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.nationality = null;
          } else {
            this.nationality = in.readString(this.nationality instanceof Utf8 ? (Utf8)this.nationality : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










