/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.szymon_kaluza.protobuf_avro.avro.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class Library extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8914843917875027256L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Library\",\"namespace\":\"com.szymon_kaluza.protobuf_avro.avro.model\",\"fields\":[{\"name\":\"address\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"books\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Book\",\"fields\":[{\"name\":\"title\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"author\",\"type\":{\"type\":\"record\",\"name\":\"Author\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"surname\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"nationality\",\"type\":[\"null\",\"string\"],\"default\":null}]}},{\"name\":\"pages\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"available\",\"type\":[\"null\",\"boolean\"],\"default\":null}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Library> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Library> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Library> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Library> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Library> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Library to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Library from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Library instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Library fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private CharSequence address;
  private java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book> books;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Library() {}

  /**
   * All-args constructor.
   * @param address The new value for address
   * @param books The new value for books
   */
  public Library(CharSequence address, java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book> books) {
    this.address = address;
    this.books = books;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return address;
    case 1: return books;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: address = (CharSequence)value$; break;
    case 1: books = (java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public CharSequence getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'books' field.
   * @return The value of the 'books' field.
   */
  public java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book> getBooks() {
    return books;
  }


  /**
   * Sets the value of the 'books' field.
   * @param value the value to set.
   */
  public void setBooks(java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book> value) {
    this.books = value;
  }

  /**
   * Creates a new Library RecordBuilder.
   * @return A new Library RecordBuilder
   */
  public static com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder newBuilder() {
    return new com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder();
  }

  /**
   * Creates a new Library RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Library RecordBuilder
   */
  public static com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder newBuilder(com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder other) {
    if (other == null) {
      return new com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder();
    } else {
      return new com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder(other);
    }
  }

  /**
   * Creates a new Library RecordBuilder by copying an existing Library instance.
   * @param other The existing instance to copy.
   * @return A new Library RecordBuilder
   */
  public static com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder newBuilder(com.szymon_kaluza.protobuf_avro.avro.model.Library other) {
    if (other == null) {
      return new com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder();
    } else {
      return new com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder(other);
    }
  }

  /**
   * RecordBuilder for Library instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Library>
    implements org.apache.avro.data.RecordBuilder<Library> {

    private CharSequence address;
    private java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book> books;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.books)) {
        this.books = data().deepCopy(fields()[1].schema(), other.books);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Library instance
     * @param other The existing instance to copy.
     */
    private Builder(com.szymon_kaluza.protobuf_avro.avro.model.Library other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.books)) {
        this.books = data().deepCopy(fields()[1].schema(), other.books);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public CharSequence getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder setAddress(CharSequence value) {
      validate(fields()[0], value);
      this.address = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder clearAddress() {
      address = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'books' field.
      * @return The value.
      */
    public java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book> getBooks() {
      return books;
    }


    /**
      * Sets the value of the 'books' field.
      * @param value The value of 'books'.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder setBooks(java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book> value) {
      validate(fields()[1], value);
      this.books = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'books' field has been set.
      * @return True if the 'books' field has been set, false otherwise.
      */
    public boolean hasBooks() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'books' field.
      * @return This builder.
      */
    public com.szymon_kaluza.protobuf_avro.avro.model.Library.Builder clearBooks() {
      books = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Library build() {
      try {
        Library record = new Library();
        record.address = fieldSetFlags()[0] ? this.address : (CharSequence) defaultValue(fields()[0]);
        record.books = fieldSetFlags()[1] ? this.books : (java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Library>
    WRITER$ = (org.apache.avro.io.DatumWriter<Library>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Library>
    READER$ = (org.apache.avro.io.DatumReader<Library>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.address == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.address);
    }

    long size0 = this.books.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.szymon_kaluza.protobuf_avro.avro.model.Book e0: this.books) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.address = null;
      } else {
        this.address = in.readString(this.address instanceof Utf8 ? (Utf8)this.address : null);
      }

      long size0 = in.readArrayStart();
      java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book> a0 = this.books;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.szymon_kaluza.protobuf_avro.avro.model.Book>((int)size0, SCHEMA$.getField("books").schema());
        this.books = a0;
      } else a0.clear();
      SpecificData.Array<com.szymon_kaluza.protobuf_avro.avro.model.Book> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.szymon_kaluza.protobuf_avro.avro.model.Book>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.szymon_kaluza.protobuf_avro.avro.model.Book e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.szymon_kaluza.protobuf_avro.avro.model.Book();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.address = null;
          } else {
            this.address = in.readString(this.address instanceof Utf8 ? (Utf8)this.address : null);
          }
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.szymon_kaluza.protobuf_avro.avro.model.Book> a0 = this.books;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.szymon_kaluza.protobuf_avro.avro.model.Book>((int)size0, SCHEMA$.getField("books").schema());
            this.books = a0;
          } else a0.clear();
          SpecificData.Array<com.szymon_kaluza.protobuf_avro.avro.model.Book> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.szymon_kaluza.protobuf_avro.avro.model.Book>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.szymon_kaluza.protobuf_avro.avro.model.Book e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.szymon_kaluza.protobuf_avro.avro.model.Book();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










