// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library.proto

package com.szymon_kaluza.protobuf_avro.proto.model;

/**
 * Protobuf type {@code protobuf.Book}
 */
public final class Book extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.Book)
    BookOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Book.newBuilder() to construct.
  private Book(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Book() {
    title_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Book();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.szymon_kaluza.protobuf_avro.proto.model.LibraryProtos.internal_static_protobuf_Book_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.szymon_kaluza.protobuf_avro.proto.model.LibraryProtos.internal_static_protobuf_Book_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.szymon_kaluza.protobuf_avro.proto.model.Book.class, com.szymon_kaluza.protobuf_avro.proto.model.Book.Builder.class);
  }

  private int bitField0_;
  public static final int TITLE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>optional string title = 1;</code>
   * @return Whether the title field is set.
   */
  @java.lang.Override
  public boolean hasTitle() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>optional string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHOR_FIELD_NUMBER = 2;
  private com.szymon_kaluza.protobuf_avro.proto.model.Author author_;
  /**
   * <code>optional .protobuf.Author author = 2;</code>
   * @return Whether the author field is set.
   */
  @java.lang.Override
  public boolean hasAuthor() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .protobuf.Author author = 2;</code>
   * @return The author.
   */
  @java.lang.Override
  public com.szymon_kaluza.protobuf_avro.proto.model.Author getAuthor() {
    return author_ == null ? com.szymon_kaluza.protobuf_avro.proto.model.Author.getDefaultInstance() : author_;
  }
  /**
   * <code>optional .protobuf.Author author = 2;</code>
   */
  @java.lang.Override
  public com.szymon_kaluza.protobuf_avro.proto.model.AuthorOrBuilder getAuthorOrBuilder() {
    return author_ == null ? com.szymon_kaluza.protobuf_avro.proto.model.Author.getDefaultInstance() : author_;
  }

  public static final int PAGES_FIELD_NUMBER = 3;
  private long pages_ = 0L;
  /**
   * <code>optional int64 pages = 3;</code>
   * @return Whether the pages field is set.
   */
  @java.lang.Override
  public boolean hasPages() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int64 pages = 3;</code>
   * @return The pages.
   */
  @java.lang.Override
  public long getPages() {
    return pages_;
  }

  public static final int AVAILABLE_FIELD_NUMBER = 4;
  private boolean available_ = false;
  /**
   * <code>optional bool available = 4;</code>
   * @return Whether the available field is set.
   */
  @java.lang.Override
  public boolean hasAvailable() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional bool available = 4;</code>
   * @return The available.
   */
  @java.lang.Override
  public boolean getAvailable() {
    return available_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getAuthor());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(3, pages_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBool(4, available_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAuthor());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, pages_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, available_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.szymon_kaluza.protobuf_avro.proto.model.Book)) {
      return super.equals(obj);
    }
    com.szymon_kaluza.protobuf_avro.proto.model.Book other = (com.szymon_kaluza.protobuf_avro.proto.model.Book) obj;

    if (hasTitle() != other.hasTitle()) return false;
    if (hasTitle()) {
      if (!getTitle()
          .equals(other.getTitle())) return false;
    }
    if (hasAuthor() != other.hasAuthor()) return false;
    if (hasAuthor()) {
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
    }
    if (hasPages() != other.hasPages()) return false;
    if (hasPages()) {
      if (getPages()
          != other.getPages()) return false;
    }
    if (hasAvailable() != other.hasAvailable()) return false;
    if (hasAvailable()) {
      if (getAvailable()
          != other.getAvailable()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTitle()) {
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
    }
    if (hasAuthor()) {
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
    }
    if (hasPages()) {
      hash = (37 * hash) + PAGES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPages());
    }
    if (hasAvailable()) {
      hash = (37 * hash) + AVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAvailable());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.szymon_kaluza.protobuf_avro.proto.model.Book parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.szymon_kaluza.protobuf_avro.proto.model.Book prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.Book}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.Book)
      com.szymon_kaluza.protobuf_avro.proto.model.BookOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.szymon_kaluza.protobuf_avro.proto.model.LibraryProtos.internal_static_protobuf_Book_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.szymon_kaluza.protobuf_avro.proto.model.LibraryProtos.internal_static_protobuf_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.szymon_kaluza.protobuf_avro.proto.model.Book.class, com.szymon_kaluza.protobuf_avro.proto.model.Book.Builder.class);
    }

    // Construct using com.szymon_kaluza.protobuf.proto.model.Book.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAuthorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      title_ = "";
      author_ = null;
      if (authorBuilder_ != null) {
        authorBuilder_.dispose();
        authorBuilder_ = null;
      }
      pages_ = 0L;
      available_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.szymon_kaluza.protobuf_avro.proto.model.LibraryProtos.internal_static_protobuf_Book_descriptor;
    }

    @java.lang.Override
    public com.szymon_kaluza.protobuf_avro.proto.model.Book getDefaultInstanceForType() {
      return com.szymon_kaluza.protobuf_avro.proto.model.Book.getDefaultInstance();
    }

    @java.lang.Override
    public com.szymon_kaluza.protobuf_avro.proto.model.Book build() {
      com.szymon_kaluza.protobuf_avro.proto.model.Book result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.szymon_kaluza.protobuf_avro.proto.model.Book buildPartial() {
      com.szymon_kaluza.protobuf_avro.proto.model.Book result = new com.szymon_kaluza.protobuf_avro.proto.model.Book(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.szymon_kaluza.protobuf_avro.proto.model.Book result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.title_ = title_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.author_ = authorBuilder_ == null
            ? author_
            : authorBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pages_ = pages_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.available_ = available_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.szymon_kaluza.protobuf_avro.proto.model.Book) {
        return mergeFrom((com.szymon_kaluza.protobuf_avro.proto.model.Book)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.szymon_kaluza.protobuf_avro.proto.model.Book other) {
      if (other == com.szymon_kaluza.protobuf_avro.proto.model.Book.getDefaultInstance()) return this;
      if (other.hasTitle()) {
        title_ = other.title_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasAuthor()) {
        mergeAuthor(other.getAuthor());
      }
      if (other.hasPages()) {
        setPages(other.getPages());
      }
      if (other.hasAvailable()) {
        setAvailable(other.getAvailable());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getAuthorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              pages_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              available_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object title_ = "";
    /**
     * <code>optional string title = 1;</code>
     * @return Whether the title field is set.
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.szymon_kaluza.protobuf_avro.proto.model.Author author_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.szymon_kaluza.protobuf_avro.proto.model.Author, com.szymon_kaluza.protobuf_avro.proto.model.Author.Builder, com.szymon_kaluza.protobuf_avro.proto.model.AuthorOrBuilder> authorBuilder_;
    /**
     * <code>optional .protobuf.Author author = 2;</code>
     * @return Whether the author field is set.
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .protobuf.Author author = 2;</code>
     * @return The author.
     */
    public com.szymon_kaluza.protobuf_avro.proto.model.Author getAuthor() {
      if (authorBuilder_ == null) {
        return author_ == null ? com.szymon_kaluza.protobuf_avro.proto.model.Author.getDefaultInstance() : author_;
      } else {
        return authorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protobuf.Author author = 2;</code>
     */
    public Builder setAuthor(com.szymon_kaluza.protobuf_avro.proto.model.Author value) {
      if (authorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        author_ = value;
      } else {
        authorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .protobuf.Author author = 2;</code>
     */
    public Builder setAuthor(
        com.szymon_kaluza.protobuf_avro.proto.model.Author.Builder builderForValue) {
      if (authorBuilder_ == null) {
        author_ = builderForValue.build();
      } else {
        authorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .protobuf.Author author = 2;</code>
     */
    public Builder mergeAuthor(com.szymon_kaluza.protobuf_avro.proto.model.Author value) {
      if (authorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          author_ != null &&
          author_ != com.szymon_kaluza.protobuf_avro.proto.model.Author.getDefaultInstance()) {
          getAuthorBuilder().mergeFrom(value);
        } else {
          author_ = value;
        }
      } else {
        authorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .protobuf.Author author = 2;</code>
     */
    public Builder clearAuthor() {
      bitField0_ = (bitField0_ & ~0x00000002);
      author_ = null;
      if (authorBuilder_ != null) {
        authorBuilder_.dispose();
        authorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .protobuf.Author author = 2;</code>
     */
    public com.szymon_kaluza.protobuf_avro.proto.model.Author.Builder getAuthorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getAuthorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protobuf.Author author = 2;</code>
     */
    public com.szymon_kaluza.protobuf_avro.proto.model.AuthorOrBuilder getAuthorOrBuilder() {
      if (authorBuilder_ != null) {
        return authorBuilder_.getMessageOrBuilder();
      } else {
        return author_ == null ?
            com.szymon_kaluza.protobuf_avro.proto.model.Author.getDefaultInstance() : author_;
      }
    }
    /**
     * <code>optional .protobuf.Author author = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.szymon_kaluza.protobuf_avro.proto.model.Author, com.szymon_kaluza.protobuf_avro.proto.model.Author.Builder, com.szymon_kaluza.protobuf_avro.proto.model.AuthorOrBuilder>
        getAuthorFieldBuilder() {
      if (authorBuilder_ == null) {
        authorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.szymon_kaluza.protobuf_avro.proto.model.Author, com.szymon_kaluza.protobuf_avro.proto.model.Author.Builder, com.szymon_kaluza.protobuf_avro.proto.model.AuthorOrBuilder>(
                getAuthor(),
                getParentForChildren(),
                isClean());
        author_ = null;
      }
      return authorBuilder_;
    }

    private long pages_ ;
    /**
     * <code>optional int64 pages = 3;</code>
     * @return Whether the pages field is set.
     */
    @java.lang.Override
    public boolean hasPages() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 pages = 3;</code>
     * @return The pages.
     */
    @java.lang.Override
    public long getPages() {
      return pages_;
    }
    /**
     * <code>optional int64 pages = 3;</code>
     * @param value The pages to set.
     * @return This builder for chaining.
     */
    public Builder setPages(long value) {

      pages_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 pages = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPages() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pages_ = 0L;
      onChanged();
      return this;
    }

    private boolean available_ ;
    /**
     * <code>optional bool available = 4;</code>
     * @return Whether the available field is set.
     */
    @java.lang.Override
    public boolean hasAvailable() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool available = 4;</code>
     * @return The available.
     */
    @java.lang.Override
    public boolean getAvailable() {
      return available_;
    }
    /**
     * <code>optional bool available = 4;</code>
     * @param value The available to set.
     * @return This builder for chaining.
     */
    public Builder setAvailable(boolean value) {

      available_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool available = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailable() {
      bitField0_ = (bitField0_ & ~0x00000008);
      available_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.Book)
  }

  // @@protoc_insertion_point(class_scope:protobuf.Book)
  private static final com.szymon_kaluza.protobuf_avro.proto.model.Book DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.szymon_kaluza.protobuf_avro.proto.model.Book();
  }

  public static com.szymon_kaluza.protobuf_avro.proto.model.Book getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Book>
      PARSER = new com.google.protobuf.AbstractParser<Book>() {
    @java.lang.Override
    public Book parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Book> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Book> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.szymon_kaluza.protobuf_avro.proto.model.Book getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

