// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library.proto

package com.szymon_kaluza.protobuf_avro.proto.model;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string title = 1;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>optional string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional .protobuf.Author author = 2;</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <code>optional .protobuf.Author author = 2;</code>
   * @return The author.
   */
  com.szymon_kaluza.protobuf_avro.proto.model.Author getAuthor();
  /**
   * <code>optional .protobuf.Author author = 2;</code>
   */
  com.szymon_kaluza.protobuf_avro.proto.model.AuthorOrBuilder getAuthorOrBuilder();

  /**
   * <code>optional int64 pages = 3;</code>
   * @return Whether the pages field is set.
   */
  boolean hasPages();
  /**
   * <code>optional int64 pages = 3;</code>
   * @return The pages.
   */
  long getPages();

  /**
   * <code>optional bool available = 4;</code>
   * @return Whether the available field is set.
   */
  boolean hasAvailable();
  /**
   * <code>optional bool available = 4;</code>
   * @return The available.
   */
  boolean getAvailable();
}
