// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library.proto

package com.szymon_kaluza.protobuf_avro.proto.model;

public interface LibraryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.Library)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string address = 1;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  java.util.List<com.szymon_kaluza.protobuf_avro.proto.model.Book>
      getBooksList();
  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  com.szymon_kaluza.protobuf_avro.proto.model.Book getBooks(int index);
  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  int getBooksCount();
  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  java.util.List<? extends com.szymon_kaluza.protobuf_avro.proto.model.BookOrBuilder>
      getBooksOrBuilderList();
  /**
   * <code>repeated .protobuf.Book books = 2;</code>
   */
  com.szymon_kaluza.protobuf_avro.proto.model.BookOrBuilder getBooksOrBuilder(
      int index);
}
